// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvtCKFuJ9s0jKWIyd1HMM3UMTJHwhRiuU',
    appId: '1:909482431750:web:d08a4042a5f81f1431fa87',
    messagingSenderId: '909482431750',
    projectId: 'vehicle-manager-25ce5',
    authDomain: 'vehicle-manager-25ce5.firebaseapp.com',
    storageBucket: 'vehicle-manager-25ce5.appspot.com',
    measurementId: 'G-208JVDRRLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYT6fQBSDEIRMHoyzwMki17myQ7lLFwo',
    appId: '1:909482431750:android:0205e9873885c56231fa87',
    messagingSenderId: '909482431750',
    projectId: 'vehicle-manager-25ce5',
    storageBucket: 'vehicle-manager-25ce5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN_tYVpCvhbASAa54mTvVYuXh326Nn8BI',
    appId: '1:909482431750:ios:2c150f0f81d61a5f31fa87',
    messagingSenderId: '909482431750',
    projectId: 'vehicle-manager-25ce5',
    storageBucket: 'vehicle-manager-25ce5.appspot.com',
    androidClientId: '909482431750-d7oerpi21mm307bje6up4q7utc26rqct.apps.googleusercontent.com',
    iosClientId: '909482431750-kvd0ih2krv25idgcb7li027fc19fpoug.apps.googleusercontent.com',
    iosBundleId: 'com.example.link',
  );

}